name: Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
         while true
         do
          python main.py
          echo "Bot crashed. Restarting..."
          sleep 5
         done

      - name: Save database
        run: |
          git add archives.db
          git commit -m "Update database" || echo "No changes"
          git push
